name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.2', '3.3']
        rails: ['7.0', '7.1', '7.2', '8.0']
        exclude:
          - ruby: '2.7'
            rails: '8.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install deps
      run: |
        sudo apt update -y
        sudo apt install -y libsqlite3-dev

    - name: Compile & test
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
      run: |
        bundle exec rake

